public enum TokenType {
    nb,
    KEYWORD,
    id,
    ASSIGNMENT_OPERATOR,
    RELATIONAL_OPERATOR,
    SEMICOLON,
    LEFT_PAREN,
    RIGHT_PAREN,
    LEFT_BRACE,
    RIGHT_BRACE,
    SUBTRACTIVE_OPERATOR,
    ADDITIVE_OPERATOR, REAL,l, FORMAT_SPECIFIER, PERCENTAGE, EQUAL, DECREMENT_OPERATOR, INCREMENT_OPERATOR, COMMA, REFERENCE, DIVISION,
}
